In [1]:
import numpy as np
a = np.random.randint(10,51,50)
a

array([35, 16, 23, 42, 45, 17, 14, 19, 49, 46, 47, 43, 11, 30, 22, 27, 32,
       46, 46, 43, 27, 45, 34, 30, 34, 41, 41, 50, 29, 46, 29, 48, 40, 26,
       34, 25, 43, 30, 27, 45, 25, 48, 30, 43, 43, 28, 21, 49, 11, 41],
      dtype=int32)

In [2]:
b = np.random.randint(10,51,50)
b

array([46, 49, 15, 39, 22, 27, 17, 23, 15, 32, 24, 30, 47, 30, 15, 49, 15,
       44, 42, 22, 39, 24, 37, 25, 45, 43, 36, 34, 13, 37, 15, 32, 29, 34,
       16, 17, 30, 50, 41, 42, 37, 49, 24, 31, 15, 33, 36, 34, 14, 14],
      dtype=int32)

In [4]:
w = np.random.randint(2,20, 40)
w

array([18, 10, 13, 13,  4,  4,  8, 15,  8, 12,  8, 17,  2, 11,  4, 11, 17,
       17, 13,  8, 10, 18,  6,  3, 18,  5,  8, 14,  3, 10, 14,  7, 13, 19,
       19, 19, 19, 18, 10, 16], dtype=int32)

In [7]:
def add(x1,x2):
    return x1 + x2

In [8]:
add(a,b)

array([81, 65, 38, 81, 67, 44, 31, 42, 64, 78, 71, 73, 58, 60, 37, 76, 47,
       90, 88, 65, 66, 69, 71, 55, 79, 84, 77, 84, 42, 83, 44, 80, 69, 60,
       50, 42, 73, 80, 68, 87, 62, 97, 54, 74, 58, 61, 57, 83, 25, 55],
      dtype=int32)

In [10]:
def categorize(x):
    if x < 0:
        return "Negative"
    elif x ==0:
        return "Neutral"
    else:
        return "Positive"

In [13]:
categorize(1)

'Positive'

In [14]:
a <0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])