In [17]:
import numpy as np
from PIL import Image

In [8]:
#task1
farenheit_array = np.array([32, 68, 100, 212, 77])
def farenheit_to_celsius(farenheit):
    return round((farenheit - 32) *5/9)
vectorized_farenheit_array = np.vectorize(farenheit_to_celsius)
vectorized_farenheit_array(farenheit_array)

array([  0,  20,  38, 100,  25])

In [12]:
#task2
numbers = np.array([2,3,4,5])
powers = np.array([1,2,3,4])
def num_to_pow(num, pow):
    return num**pow
vectorized_func = np.vectorize(num_to_pow)
vectorized_func(numbers, powers)

array([  2,   9,  64, 625])

In [15]:
#task3
A = np.array([
    [4,5,6],
    [3,-1,1],
    [2,1,-2]
])
b = np.array([7,4,5])
np.linalg.solve(A, b)

array([ 1.7027027 ,  0.62162162, -0.48648649])

In [16]:
#task4
C = np.array([
    [10,-2,3],
    [-2, 8, -1],
    [3,-1,6]
])
d = np.array([12,-5,15])
np.linalg.solve(A, b)

array([ 1.7027027 ,  0.62162162, -0.48648649])

In [23]:
#task5
image = Image.open("birds.jpg")
image_array = np.array(image)
def flip_image(image):
    flip_horiz = image[:,::-1,:]
    flip_vert = flip_horiz[::-1,:,:]
    output_image_h = Image.fromarray(flip_horiz)
    output_image_v = Image.fromarray(flip_vert)
    output_image_h.save("flipped_h.jpg")
    output_image_v.save("flipped_v.jpg")
def add_noise(image):
    noise = np.random.randint(-30,30, image.shape, dtype=np.int16)
    noisy_image = np.clip(image + noise, 0, 255).astype(np.uint8)
    output_image = Image.fromarray(noisy_image)
    output_image.save("noise.jpg")
def bright_channels(image):
    image[:,:,0] = np.clip(image[:,:,0] +40, 0, 255)
    output_image = Image.fromarray(image)
    output_image.save("bright_channels.jpg")
def mask(image):
    height, width, _ = image.shape
    x_start, y_start = width//2 -50, height//2 - 50
    x_end, y_end = x_start+100, y_start+100
    image[y_start:y_end, x_start:x_end, :] = 0
    output_image = Image.fromarray(image)
    output_image.save("mask.jpg")

if __name__ == '__main__':
    flip_image(image_array)
    add_noise(image_array)
    bright_channels(image_array)
    mask(image_array)