In [1]:
import numpy as np
array = np.random.rand(30,30)
print(array[10,20])

0.9709324788658992


In [2]:
import numpy as np
array = np.random.rand(30,30)
total_sum = np.sum(array)
print(total_sum)

450.31966442310244


In [5]:
import numpy as np
array = np.random.rand(30,30)
first_ten = array[:10]
mean_first_ten = np.mean(first_ten)
print(mean_first_ten)

0.49112083906388165


In [7]:
import numpy as np
def simulate_fair_coin_flips():
    flips = np.random.randint(0,2, size=1000)
    return flips
flips = simulate_fair_coin_flips()
print(flips)

[1 1 1 0 0 1 1 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1
 1 1 0 1 1 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1 1 1 1 0 1 1 1
 1 1 1 1 1 0 0 1 0 1 1 0 1 0 1 0 1 1 0 0 0 1 1 1 0 1 1 0 1 1 1 1 0 0 0 0 1
 1 1 0 0 1 0 0 1 0 1 1 1 1 0 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 0 1 1 1
 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 1 1 1 0 0 1
 0 1 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 1 1 0 1 1 0 0 1 0 0 1 0 0 1 1 1
 1 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 1 1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 1 0 1 0 0
 0 0 0 0 1 0 0 1 1 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 0 0 0 0 0 1 0 0 1 0 1
 0 1 0 1 0 1 1 0 1 1 1 1 0 0 1 0 1 1 1 1 0 0 1 0 1 0 0 1 1 0 1 0 0 1 1 1 1
 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0
 1 0 0 1 0 1 1 0 1 0 1 0 0 1 1 0 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 1 1 0 1 1 0
 1 0 1 0 1 0 1 0 0 0 0 1 1 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 0 0 0 0 1 1 0 1
 0 0 0 0 1 1 1 0 1 1 1 0 0 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 0 1 1 0 0 1
 1 0 1 0 1 1 0 0 1 1 0 0 

In [11]:
import numpy as np
def simulate_biased_coin_flips():
    flips = np.random.choice([1,0], size=[1000], p=[0.7, 0.3])
    return flips
flips = simulate_biased_coin_flips()
print(flips)

[0 1 0 1 1 1 1 0 0 1 0 1 1 1 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 0
 1 0 1 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 1 0 1 0 0 0 0 1 0 1 1 1
 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 1 1 1 0 0 1 1
 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 1
 1 1 1 0 1 1 1 0 1 1 0 1 0 0 0 0 1 1 1 1 1 0 0 1 1 0 0 1 0 1 1 0 0 1 1 1 1
 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 0 1 1 0 1 0 1 1 0 0 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 1
 1 0 0 0 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 1 1
 1 1 1 1 1 0 0 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 0 1 1 1 1 1 1 0 1 0 1 1 1 0
 0 0 0 0 1 1 1 1 1 1 0 1 1 0 0 1 0 0 1 1 0 1 0 1 1 0 1 0 1 1 1 0 1 1 1 1 1
 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1
 1 0 1 1 1 0 0 1 1 1 0 0 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 0 0 1 1 0 0 0 1 1 1
 0 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 1 0 1 0 0 1 1
 0 1 0 1 1 1 1 1 1 1 1 1 

In [15]:
import numpy as np
def simulate_biased_coin_flips():
    flips = np.random.choice([1,0], size=1000, p=[0.7, 0.3])
    return flips
flips = simulate_biased_coin_flips()
proportion = np.mean(flips)
print(proportion)

0.7


In [46]:
import numpy as np
array = np.random.choice(range(1,11), size=5)
average = np.mean(array)
print(average)
print(array)

3.2
[3 2 5 3 3]


In [118]:
import numpy as np
def simulate_roll_dies():
    roll_dies = np.random.choice(range(1,7), size=10000, p=[1/6] *6)
    getting_six = np.sum(roll_dies==6)/10000
    return roll_dies, getting_six
rolling_dies = simulate_roll_dies()
print(rolling_dies)


(array([2, 2, 4, ..., 4, 1, 6], shape=(10000,)), np.float64(0.1704))


In [119]:
print(rolling_dies)

(array([2, 2, 4, ..., 4, 1, 6], shape=(10000,)), np.float64(0.1704))


In [124]:
import numpy as np
my_array = np.random.rand(3,4)
print(my_array)
sum_of_secondrow = np.sum(my_array[1,:])
print(sum_of_secondrow)

[[0.47843712 0.74343621 0.07311552 0.99617774]
 [0.16365262 0.79041414 0.0020927  0.25314042]
 [0.88955196 0.77665255 0.69796556 0.76525374]]
1.2092998799172305


In [125]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "City": ["New York", "Los Angeles", "Chicago"]
}
df = pd.DataFrame(data)
print(df)

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago


In [126]:
print(df["Name"])
print(df["Age"])
print(df["City"])

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object
0    25
1    30
2    35
Name: Age, dtype: int64
0       New York
1    Los Angeles
2        Chicago
Name: City, dtype: object
