In [9]:
import numpy as np
import random

In [14]:
#task1
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [13]:
#task2
np.arange(0,9).reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
#task3
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#task4
np.random.random((3,3,3))

array([[[0.30518767, 0.61115735, 0.6220347 ],
        [0.86999109, 0.86296994, 0.54570673],
        [0.22611161, 0.17536328, 0.38123813]],

       [[0.44512021, 0.04867454, 0.98135169],
        [0.57499182, 0.91706955, 0.62374638],
        [0.93521828, 0.50190119, 0.66822778]],

       [[0.87196267, 0.80396683, 0.13731404],
        [0.12016405, 0.5686442 , 0.25232023],
        [0.93267731, 0.29111749, 0.48419174]]])

In [19]:
#task5
ten_dim_array = np.random.random((10,10))

np.float64(0.006896913443247832)

In [20]:
ten_dim_array

array([[0.08168159, 0.44250534, 0.80261604, 0.29363701, 0.14064713,
        0.98824825, 0.04028193, 0.59109332, 0.5493783 , 0.18136455],
       [0.96317277, 0.84552654, 0.06030479, 0.81868539, 0.97862305,
        0.44888183, 0.84633036, 0.04126074, 0.77061747, 0.08874257],
       [0.04649047, 0.57026752, 0.44660791, 0.5717337 , 0.74752315,
        0.21187371, 0.24493956, 0.18794183, 0.62414897, 0.72124827],
       [0.86067584, 0.79727009, 0.04374365, 0.4016632 , 0.01023225,
        0.21029942, 0.54870887, 0.00689691, 0.38649554, 0.84316221],
       [0.94674508, 0.77316944, 0.972403  , 0.39488249, 0.40004025,
        0.27419035, 0.41679346, 0.8998432 , 0.19994469, 0.69547255],
       [0.82764607, 0.45823242, 0.34082767, 0.3973013 , 0.86638875,
        0.84260898, 0.09050579, 0.68005579, 0.49084051, 0.19844992],
       [0.43897632, 0.66934179, 0.74221375, 0.33793911, 0.29424857,
        0.55742016, 0.37222785, 0.5714334 , 0.60304606, 0.59781582],
       [0.67884516, 0.28379143, 0.6058142

In [21]:
ten_dim_array.max()

np.float64(0.9882482456815188)

In [22]:
ten_dim_array.min()

np.float64(0.006896913443247832)

In [23]:
#task6
vector_size_thirty = np.random.random(30)
vector_size_thirty

array([0.51992915, 0.47423756, 0.36364333, 0.31981659, 0.28300218,
       0.80067994, 0.62613802, 0.51939389, 0.97031149, 0.90568535,
       0.65003857, 0.96546195, 0.39362414, 0.19775901, 0.13156052,
       0.97708673, 0.62901059, 0.8893378 , 0.48911484, 0.63134198,
       0.1572529 , 0.86647049, 0.74565777, 0.61642206, 0.29118415,
       0.24934604, 0.80159575, 0.15849787, 0.04397718, 0.02098396])

In [24]:
vector_size_thirty.mean()

np.float64(0.5229520588787694)

In [25]:
#task7
five_dim_matrix = np.random.random((5,5))
norm_matrix = (five_dim_matrix - five_dim_matrix.min())/(five_dim_matrix.max() - five_dim_matrix.min())
norm_matrix

array([[0.77514363, 0.87042368, 0.07672823, 0.51849724, 0.64375795],
       [0.52749925, 0.4763696 , 0.19283018, 0.4667407 , 0.        ],
       [0.04742637, 0.42408554, 0.82834441, 0.56288357, 0.58954988],
       [0.65300256, 0.05297036, 1.        , 0.6049459 , 0.92837804],
       [0.41522957, 0.53670494, 0.01150999, 0.56770397, 0.52536056]])

In [28]:
#task8
five_by_three = np.random.random((5,3))
three_by_two = np.random.random((3,2))
np.dot(five_by_three, three_by_two)

array([[0.80186653, 0.62113644],
       [1.53703707, 1.00973415],
       [0.29535456, 0.21550384],
       [1.43217241, 1.02586372],
       [0.60880827, 0.35654224]])

In [29]:
#task9
first_three_d = np.random.random((3,3))
second_three_d = np.random.random((3,3))
np.dot(first_three_d, second_three_d)

array([[0.45679908, 0.81370741, 0.95968547],
       [1.30620049, 1.48510777, 1.31747708],
       [0.71715023, 1.11293259, 0.85325981]])

In [30]:
#task10
four_by_four = np.random.random((4,4))
np.transpose(four_by_four)


array([[0.2804307 , 0.24703038, 0.15165934, 0.57861679],
       [0.57346205, 0.41823564, 0.29520576, 0.53576645],
       [0.53764654, 0.8999883 , 0.045332  , 0.91432481],
       [0.36049245, 0.18930557, 0.95923044, 0.02712727]])

In [32]:
#task11
three_by_three = np.random.random((3,3))
np.linalg.det(three_by_three)

np.float64(0.47135724355666897)

In [33]:
#task12
three_by_four = np.random.random((3,3))
four_by_three = np.random.random((3,3))
np.matmul(three_by_four, four_by_three)

array([[1.15355666, 1.08313692, 0.76120416],
       [0.89697868, 1.1249778 , 0.58005468],
       [0.76577651, 0.98173512, 0.54552667]])

In [36]:
#task13
three_by_three = np.random.random((3,3))
one_dim = np.random.random((3,1))
np.matmul(three_by_three, one_dim)

array([[0.64977277],
       [0.58351213],
       [0.82705076]])

In [40]:
#task14
a = np.random.random((3,3))
b = np.random.random((3,1))
x = np.linalg.solve(a, b)
x

array([[ 1.38490543],
       [-1.17975104],
       [ 0.19739502]])

In [42]:
#task15
five_by_five = np.random.random((5,5))
np.sum(five_by_five, axis = 0) #rows

array([2.89027595, 3.31100136, 2.71190835, 2.03521196, 1.55740951])

In [43]:
np.sum(five_by_five, axis=1) #column

array([2.99468803, 2.76469649, 1.5521022 , 2.92977788, 2.26454253])