In [7]:
import numpy as np

In [8]:
array = [1,2,3,4,5]
array=np.array(array)
array

array([1, 2, 3, 4, 5])

In [9]:
np.arange(10,15,0.2)


array([10. , 10.2, 10.4, 10.6, 10.8, 11. , 11.2, 11.4, 11.6, 11.8, 12. ,
       12.2, 12.4, 12.6, 12.8, 13. , 13.2, 13.4, 13.6, 13.8, 14. , 14.2,
       14.4, 14.6, 14.8])

In [10]:
np.linspace(1,10,11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
c = np.array([1, "Hello"])
c.dtype

dtype('<U21')

In [14]:
ns = np.full((2,7), fill_value=10)
ns

array([[10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10]])

In [15]:
empty = np.empty((1,2))

In [16]:
np.eye(5,5) #Identity matrix 5x5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [17]:
data = np.array((1,2), dtype=int)
ones = np.ones((2))
data+ones

array([2., 3.])

In [19]:
data.shape

(2,)

In [20]:
data.max()
np.max(data) # both are same

np.int64(2)

In [21]:
data1 = np.array([
    [1,2],
    [3,4],
    [5,6]
])


array([2, 4, 6])

In [22]:
data1.max(axis=0)

array([5, 6])

In [23]:
data1.max(axis=1)

array([2, 4, 6])

In [24]:
class Array:
    def __init__(self, l: list):
        self.l = l
    def __getitem__(self, index):
        try:
            index = int(index)
            return super().__getitem__[index]
        except TypeError:
            raise
a1 = Array([1,2,3,4,5])
a1['1']

2

In [25]:
data1[0:2, 0]

array([1, 3])

In [28]:
a2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]

])
a2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
a2[1:, 2:]

array([[ 7,  8],
       [11, 12]])